import axios from 'axios';
import config from '../../config.cjs';

const paircode = async (m, sock) => {
  const prefix = config.PREFIX;
  const cmd = m.body.startsWith(prefix)
    ? m.body.slice(prefix.length).split(' ')[0].toLowerCase()
    : '';
  const number = m.body.slice(prefix.length + cmd.length).trim();

  if (!number) {
    return await sock.sendMessage(m.from, {
      text: '❌ Please provide a number.\n\nExample: *.paircode +254712345678*',
    }, { quoted: m });
  }

  try {
    const response = await axios.get(`https://popkidsessgenerator.onrender.com/pair?number=${encodeURIComponent(number)}`);
    const code = response.data.code;

    if (!code) throw 'Invalid response from session generator.';

    const msg = `✅ *Pair Code Generated!*\n\n📱 *Number:* ${number}\n🔐 *Code:* ${code}\n\n🧠 *Generated by:* Popkid-Xmd`;

    await sock.sendMessage(m.from, {
      image: { url: 'https://files.catbox.moe/959dyk.jpg' },
      caption: msg,
      contextInfo: {
        forwardingScore: 5,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
          newsletterName: "Popkid-Xmd",
          newsletterJid: "120363290715861418@newsletter",
        },
      },
    }, { quoted: m });

  } catch (e) {
    await sock.sendMessage(m.from, {
      text: `❌ Failed to generate pair code.\n${e.message || e}`,
    }, { quoted: m });
  }
};

export default paircode;
